// font_atlas.h — GENERATED by tools/gen-font.py (SFCompact.ttf). Do not edit.
#ifndef PS4CAST_FONT_ATLAS_H
#define PS4CAST_FONT_ATLAS_H

// Anti-aliased monospace glyph atlas, ASCII 32..126, indexed by text scale.
// FONT_CELL[scale] == 8*scale; FONT_DATA[scale] is 0 alpha bytes/glyph * 95
// glyphs (NULL where the 8x8 fallback should be used).
#define FONT_FIRST 32
#define FONT_LAST 126
#define FONT_MAXSCALE 6

extern const int FONT_CELL[FONT_MAXSCALE + 1];
extern const unsigned char *const FONT_ADV[FONT_MAXSCALE + 1];
extern const unsigned char *const FONT_DATA[FONT_MAXSCALE + 1];

#endif
