// web_ui.h — the phone/PC control page, embedded as a C string.
// Clean, mobile-first: paste a link, press Cast, then full transport controls.
#ifndef PS4CAST_WEB_UI_H
#define PS4CAST_WEB_UI_H

static const char WEB_UI_HTML[] =
"<!doctype html><html lang=\"en\"><head><meta charset=\"utf-8\">"
"<meta name=\"viewport\" content=\"width=device-width,initial-scale=1,viewport-fit=cover\">"
"<title>PS4 Cast</title><style>"
":root{color-scheme:dark}"
"*{box-sizing:border-box;-webkit-tap-highlight-color:transparent}"
"body{margin:0;min-height:100vh;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;"
"background:radial-gradient(1200px 600px at 50% -10%,#1b2547,#0b1020 60%);color:#e8ecf7;"
"display:flex;flex-direction:column;align-items:center;justify-content:center;padding:24px;gap:16px}"
".card{width:100%;max-width:440px;background:rgba(21,28,51,.85);border:1px solid #2a3760;"
"border-radius:20px;padding:24px;box-shadow:0 20px 60px rgba(0,0,0,.45);backdrop-filter:blur(8px)}"
".brand{display:flex;align-items:center;gap:11px;margin-bottom:18px}"
".dot{width:11px;height:11px;border-radius:50%;background:#36d399;box-shadow:0 0 10px #36d399}"
".dot.off{background:#6b7280;box-shadow:none}"
"h1{margin:0;font-size:21px;font-weight:700}"
".tag{margin-left:auto;font-size:11px;color:#7c89b8}"
"label{display:block;font-size:12px;color:#8b97c4;margin:0 0 7px;font-weight:600}"
"input[type=url]{width:100%;padding:15px;border-radius:13px;border:1px solid #2f3c72;"
"background:#0d1326;color:#fff;font-size:16px;outline:none}"
"input[type=url]:focus{border-color:#3b82f6}"
".urlrow{display:flex;gap:9px;align-items:stretch}"
".urlrow input{flex:1;min-width:0}"
".paste{flex:0 0 auto;padding:0 17px;border-radius:13px;border:1px solid #2f3c72;"
"background:#1d2645;color:#cdd6f4;font-weight:700;font-size:14px;cursor:pointer}"
".paste:active{transform:scale(.96)}"
".row{display:flex;gap:11px;margin-top:14px}"
"button{flex:1;padding:15px;border:0;border-radius:13px;font-size:15px;font-weight:700;cursor:pointer;transition:transform .06s}"
"button:active{transform:scale(.96)}"
".cast{background:linear-gradient(180deg,#3b82f6,#2563eb);color:#fff}"
".ghost{background:#1d2645;color:#cdd6f4;border:1px solid #2f3c72}"
/* transport */
".xport{margin-top:20px;padding-top:18px;border-top:1px solid #283358;opacity:.45;pointer-events:none;transition:opacity .2s}"
".xport.on{opacity:1;pointer-events:auto}"
".seek{width:100%;-webkit-appearance:none;height:6px;border-radius:6px;background:#27304f;outline:none}"
".seek::-webkit-slider-thumb{-webkit-appearance:none;width:18px;height:18px;border-radius:50%;background:#3b82f6;box-shadow:0 0 0 4px rgba(59,130,246,.25)}"
".seek::-moz-range-thumb{width:18px;height:18px;border:0;border-radius:50%;background:#3b82f6}"
".time{display:flex;justify-content:space-between;font:12px monospace;color:#8b97c4;margin-top:7px}"
".tbtns{display:flex;gap:10px;margin-top:14px;align-items:center}"
".tbtns button{flex:1}"
".pp{flex:1.4!important;background:#3b82f6;color:#fff}"
".status{margin-top:16px;display:flex;align-items:center;gap:9px;font-size:14px;color:#aeb9e4;min-height:20px}"
".spin{width:15px;height:15px;border:2px solid #34406e;border-top-color:#3b82f6;border-radius:50%;animation:s .7s linear infinite;display:none}@keyframes s{to{transform:rotate(360deg)}}"
".hint{font-size:12px;color:#69749f;margin-top:12px;line-height:1.5}"
"</style></head><body>"
"<div class=\"card\">"
"<div class=\"brand\"><span class=\"dot off\" id=\"dot\"></span><h1>PS4 Cast</h1><span class=\"tag\" id=\"tag\">\xe2\x80\xa6</span></div>"
"<label for=\"u\">Video link</label>"
"<div class=\"urlrow\">"
"<input id=\"u\" type=\"url\" inputmode=\"url\" placeholder=\"https://\xe2\x80\xa6/movie.mp4\" autocomplete=\"off\" autocapitalize=\"off\" spellcheck=\"false\">"
"<button class=\"paste\" onclick=\"paste()\">Paste</button></div>"
"<div class=\"row\"><button class=\"cast\" onclick=\"cast()\">Cast</button>"
"<button class=\"ghost\" onclick=\"fav()\" title=\"Favorite\">\xe2\x98\x85</button>"
"<button class=\"ghost\" onclick=\"queue()\" title=\"Play next\">+Q</button></div>"
"<div id=\"lists\" style=\"margin-top:14px\"></div>"
"<div class=\"xport\" id=\"xp\">"
"<input class=\"seek\" id=\"sk\" type=\"range\" min=\"0\" max=\"100\" value=\"0\" step=\"1\">"
"<div class=\"time\"><span id=\"cur\">0:00</span><span id=\"dur\">0:00</span></div>"
"<div class=\"tbtns\">"
"<button class=\"ghost\" onclick=\"skip(-15)\">\xe2\x97\x84 15</button>"
"<button class=\"pp\" id=\"pp\" onclick=\"toggle()\">\xe2\x9d\x9a\xe2\x9d\x9a</button>"
"<button class=\"ghost\" onclick=\"skip(15)\">15 \xe2\x96\xba</button>"
"<button class=\"ghost\" onclick=\"stop()\">\xe2\x96\xa0</button>"
"</div></div>"
"<div class=\"status\"><span class=\"spin\" id=\"spin\"></span><span id=\"msg\">Ready</span></div>"
"<div class=\"hint\">Paste a direct video link (MP4, MKV, HLS) over http or https.</div>"
"</div>"
"<script>"
"var $=function(i){return document.getElementById(i)};var drag=false,dur=0;"
"function busy(b){$('spin').style.display=b?'inline-block':'none'}"
"function msg(t){$('msg').textContent=t}"
"function fmt(s){s=Math.max(0,s|0);var m=(s/60)|0,x=s%60;return m+':' + (x<10?'0':'')+x}"
"async function post(p,b){try{return await fetch(p,{method:'POST',headers:{'Content-Type':'text/plain'},body:b||''})}catch(e){}}"
"async function cast(){var u=$('u').value.trim();if(!u){msg('Enter a link first');return}busy(true);msg('Casting\xe2\x80\xa6');await post('/avplay',u)}"
"async function paste(){try{var t=await navigator.clipboard.readText();if(t){$('u').value=t.trim();msg('Pasted')}else{msg('Clipboard empty')}}catch(e){msg('Long-press the field to paste')}}"
"async function stop(){busy(false);await post('/stop');msg('Stopped')}"
"async function toggle(){await post('/pause')}"
"async function skip(d){var v=Math.max(0,(+$('sk').value)+d);$('sk').value=v;await post('/seek',''+v)}"
"async function fav(){var u=$('u').value.trim();if(u){await post('/fav',u);loadLists()}}"
"async function queue(){var u=$('u').value.trim();if(u){await post('/queue',u);msg('Queued')}}"
"function shorten(u){try{u=decodeURIComponent(u)}catch(e){}return u.length>54?u.slice(0,30)+'\xe2\x80\xa6'+u.slice(-20):u}"
"function rowsHtml(t,a){if(!a||!a.length)return '';var h='<div style=\"font-size:11px;color:#7c89b8;margin:10px 0 4px;text-transform:uppercase\">'+t+'</div>';"
"for(var i=0;i<a.length;i++){h+='<div onclick=\"pick(\\''+encodeURIComponent(a[i])+'\\')\" style=\"padding:8px 10px;margin:4px 0;background:#0e1428;border:1px solid #232c4f;border-radius:9px;font-size:12px;color:#aeb9e4;cursor:pointer;word-break:break-all\">'+shorten(a[i])+'</div>'}return h}"
"function pick(u){try{u=decodeURIComponent(u)}catch(e){}$('u').value=u;cast()}"
"async function loadLists(){try{var f=await(await fetch('/favs')).json();var r=await(await fetch('/recent')).json();$('lists').innerHTML=rowsHtml('\xe2\x98\x85 Favorites',f)+rowsHtml('Recent',r)}catch(e){}}"
"$('sk').addEventListener('input',function(){drag=true;$('cur').textContent=fmt(+$('sk').value)});"
"$('sk').addEventListener('change',async function(){await post('/seek',''+$('sk').value);drag=false});"
"async function poll(){try{var r=await fetch('/status');var j=await r.json();"
"var on=j.active==1||j.paused==1;$('dot').className='dot'+(on?'':' off');$('tag').textContent='v'+j.ver;"
"$('xp').className='xport'+(on?' on':'');"
"$('pp').innerHTML=j.paused==1?'\xe2\x96\xba':'\xe2\x9d\x9a\xe2\x9d\x9a';"
"if(j.dur){dur=j.dur;$('sk').max=j.dur;$('dur').textContent=fmt(j.dur)}"
"if(!drag&&j.cur!=null){$('sk').value=j.cur;$('cur').textContent=fmt(j.cur)}"
"if(j.status){msg(j.status);busy(/buffer|cast|connect|seek|open/i.test(j.status)&&!on)}"
"}catch(e){}}"
"setInterval(poll,1000);poll();loadLists();setInterval(loadLists,5000);"
"</script></body></html>";

#endif
