port=8200
network_interface=en0
friendly_name=PS4 Cast ReadyMedia
media_dir=V,/Users/macbook/dev/ps4-cast/app/assets
db_dir=/private/tmp/ps4cast-minidlna-db
log_dir=/private/tmp
inotify=no
strict_dlna=no
presentation_url=http://192.168.1.139:8200/
