#!/usr/bin/env python3
# Generate app/src/font_atlas.c/.h: an anti-aliased glyph atlas baked from a
# real UI font, so the on-screen PS4 UI text is readable instead of
# the 8x8 bitmap. Run once with a Pillow-enabled python:
#   python3 -m venv /tmp/fontvenv && /tmp/fontvenv/bin/pip install Pillow
#   /tmp/fontvenv/bin/python tools/gen-font.py
#
# Each glyph (ASCII 32..126) is rendered on a common baseline into an
# (8*scale)x(8*scale) alpha cell. A matching advance table gives proportional
# spacing, which is much more readable on the TV than fixed 8-column cells.
import os
from PIL import Image, ImageDraw, ImageFont

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_C = os.path.join(ROOT, "app", "src", "font_atlas.c")
OUT_H = os.path.join(ROOT, "app", "src", "font_atlas.h")

# Prefer readable humanist/system UI fonts. The generated advance table makes
# these work cleanly in the PS4 renderer without the old spaced-out cell look.
FONT_CANDIDATES = [
    "/System/Library/Fonts/SFCompact.ttf",
    "/System/Library/Fonts/SFNS.ttf",
    "/System/Library/Fonts/Avenir.ttc",
    "/System/Library/Fonts/HelveticaNeue.ttc",
    "/System/Library/Fonts/LucidaGrande.ttc",
    "/System/Library/Fonts/SFNSMono.ttf",
    "/System/Library/Fonts/Menlo.ttc",
    "/System/Library/Fonts/Monaco.ttf",
    "/Library/Fonts/Menlo.ttc",
]
SCALES = [2, 3, 4, 5, 6]          # cells 16,24,32,40,48 (scale 1 keeps font8x8)
FIRST, LAST = 32, 126

def load_font(px):
    for path in FONT_CANDIDATES:
        if os.path.exists(path):
            try:
                return ImageFont.truetype(path, px), path
            except Exception:
                continue
    raise SystemExit("no usable monospace font found")

def render_scale(scale):
    cell = 8 * scale
    # Largest pixel size whose ascent+descent fits the cell with a little air.
    px = cell
    while px > 4:
        font, path = load_font(px)
        asc, desc = font.getmetrics()
        if asc + desc <= int(cell * 0.96):
            break
        px -= 1
    font, path = load_font(px)
    asc, desc = font.getmetrics()
    baseline = asc + (cell - (asc + desc)) // 2
    data = bytearray()
    advs = []
    for cp in range(FIRST, LAST + 1):
        img = Image.new("L", (cell, cell), 0)
        d = ImageDraw.Draw(img)
        ch = chr(cp)
        adv = font.getlength(ch)
        bbox = font.getbbox(ch, anchor="ls")
        bx0 = bbox[0] if bbox else 0
        pad = max(1, scale // 2)
        x = pad - bx0
        try:
            d.text((x, baseline), ch, fill=255, font=font, anchor="ls")
        except Exception:
            d.text((x, baseline - asc), ch, fill=255, font=font)
        width = int(round(adv)) + pad
        if ch == " ":
            width = int(round(font.getlength("n") * 0.55))
        if width < scale * 2:
            width = scale * 2
        if width > cell:
            width = cell
        advs.append(width)
        data.extend(img.tobytes())
    return cell, data, advs, os.path.basename(path), px

def main():
    scales_out = {}
    fontname = ""
    for s in SCALES:
        cell, data, advs, fname, px = render_scale(s)
        scales_out[s] = (cell, data, advs)
        fontname = fname
        print("scale %d: cell=%d px=%d bytes=%d" % (s, cell, px, len(data)))

    with open(OUT_H, "w") as f:
        f.write("// font_atlas.h — GENERATED by tools/gen-font.py (%s). Do not edit.\n" % fontname)
        f.write("#ifndef PS4CAST_FONT_ATLAS_H\n#define PS4CAST_FONT_ATLAS_H\n\n")
        f.write("// Anti-aliased monospace glyph atlas, ASCII %d..%d, indexed by text scale.\n" % (FIRST, LAST))
        f.write("// FONT_CELL[scale] == 8*scale; FONT_DATA[scale] is %d alpha bytes/glyph * 95\n" % 0)
        f.write("// glyphs (NULL where the 8x8 fallback should be used).\n")
        f.write("#define FONT_FIRST %d\n#define FONT_LAST %d\n#define FONT_MAXSCALE 6\n\n" % (FIRST, LAST))
        f.write("extern const int FONT_CELL[FONT_MAXSCALE + 1];\n")
        f.write("extern const unsigned char *const FONT_ADV[FONT_MAXSCALE + 1];\n")
        f.write("extern const unsigned char *const FONT_DATA[FONT_MAXSCALE + 1];\n\n")
        f.write("#endif\n")

    with open(OUT_C, "w") as f:
        f.write("// font_atlas.c — GENERATED by tools/gen-font.py (%s). Do not edit.\n" % fontname)
        f.write('#include "font_atlas.h"\n\n')
        for s in SCALES:
            cell, data, advs = scales_out[s]
            f.write("static const unsigned char g_font%d_adv[%d] = {\n" % (s, len(advs)))
            f.write(",".join(str(a) for a in advs))
            f.write("\n};\n\n")
            f.write("static const unsigned char g_font%d[%d] = {\n" % (s, len(data)))
            line = []
            for i, byte in enumerate(data):
                line.append(str(byte))
                if len(line) == 32:
                    f.write(",".join(line) + ",\n"); line = []
            if line:
                f.write(",".join(line) + "\n")
            f.write("};\n\n")
        cells = ["0"] * 7
        datas = ["0"] * 7
        advs = ["0"] * 7
        for s in SCALES:
            cells[s] = str(8 * s)
            datas[s] = "g_font%d" % s
            advs[s] = "g_font%d_adv" % s
        f.write("const int FONT_CELL[FONT_MAXSCALE + 1] = {%s};\n" % ",".join(cells))
        f.write("const unsigned char *const FONT_ADV[FONT_MAXSCALE + 1] = {%s};\n" % ",".join(advs))
        f.write("const unsigned char *const FONT_DATA[FONT_MAXSCALE + 1] = {%s};\n" % ",".join(datas))

    print("wrote", OUT_C, "and", OUT_H)

if __name__ == "__main__":
    main()
