#!/usr/bin/env python3
# Generate app/src/font_atlas.c/.h: an anti-aliased glyph atlas baked from a
# real UI font, so the on-screen PS4 UI text is readable and slick instead of
# the 8x8 bitmap. Run once with a Pillow-enabled python:
#   python3 -m venv /tmp/fontvenv && /tmp/fontvenv/bin/pip install Pillow
#   /tmp/fontvenv/bin/python tools/gen-font.py
#
# Each glyph (ASCII 32..126) is rendered centered on a common baseline into an
# (8*scale)x(8*scale) alpha cell, so the cell == the old font8x8 cell and ALL
# existing layout math (gfx_text_w = n*8*scale) is preserved unchanged.
import os
from PIL import Image, ImageDraw, ImageFont

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_C = os.path.join(ROOT, "app", "src", "font_atlas.c")
OUT_H = os.path.join(ROOT, "app", "src", "font_atlas.h")

# Prefer readable humanist/system UI fonts. The renderer still uses fixed cells
# so layout stays predictable on the PS4 framebuffer, but a proportional source
# face reads less mechanical than the previous SF Mono atlas.
FONT_CANDIDATES = [
    "/System/Library/Fonts/SFCompact.ttf",
    "/System/Library/Fonts/SFNS.ttf",
    "/System/Library/Fonts/Avenir.ttc",
    "/System/Library/Fonts/HelveticaNeue.ttc",
    "/System/Library/Fonts/LucidaGrande.ttc",
    "/System/Library/Fonts/SFNSMono.ttf",
    "/System/Library/Fonts/Menlo.ttc",
    "/System/Library/Fonts/Monaco.ttf",
    "/Library/Fonts/Menlo.ttc",
]
SCALES = [2, 3, 4, 5, 6]          # cells 16,24,32,40,48 (scale 1 keeps font8x8)
FIRST, LAST = 32, 126

def load_font(px):
    for path in FONT_CANDIDATES:
        if os.path.exists(path):
            try:
                return ImageFont.truetype(path, px), path
            except Exception:
                continue
    raise SystemExit("no usable monospace font found")

def render_scale(scale):
    cell = 8 * scale
    # Largest pixel size whose ascent+descent fits the cell with a little air.
    px = cell
    while px > 4:
        font, path = load_font(px)
        asc, desc = font.getmetrics()
        if asc + desc <= int(cell * 0.96):
            break
        px -= 1
    font, path = load_font(px)
    asc, desc = font.getmetrics()
    baseline = asc + (cell - (asc + desc)) // 2
    # Use a broad but not extreme uppercase width to center glyphs inside the
    # fixed 8*scale cell. This keeps digits/labels tidy without the airy mono
    # spacing that made channel names feel too loose.
    adv = min(cell * 0.92, max(font.getlength("M"), font.getlength("0")))
    data = bytearray()
    for cp in range(FIRST, LAST + 1):
        img = Image.new("L", (cell, cell), 0)
        d = ImageDraw.Draw(img)
        ch = chr(cp)
        x = (cell - adv) / 2.0
        try:
            d.text((x, baseline), ch, fill=255, font=font, anchor="ls")
        except Exception:
            d.text((x, baseline - asc), ch, fill=255, font=font)
        data.extend(img.tobytes())
    return cell, data, os.path.basename(path), px

def main():
    scales_out = {}
    fontname = ""
    for s in SCALES:
        cell, data, fname, px = render_scale(s)
        scales_out[s] = (cell, data)
        fontname = fname
        print("scale %d: cell=%d px=%d bytes=%d" % (s, cell, px, len(data)))

    with open(OUT_H, "w") as f:
        f.write("// font_atlas.h — GENERATED by tools/gen-font.py (%s). Do not edit.\n" % fontname)
        f.write("#ifndef PS4CAST_FONT_ATLAS_H\n#define PS4CAST_FONT_ATLAS_H\n\n")
        f.write("// Anti-aliased monospace glyph atlas, ASCII %d..%d, indexed by text scale.\n" % (FIRST, LAST))
        f.write("// FONT_CELL[scale] == 8*scale; FONT_DATA[scale] is %d alpha bytes/glyph * 95\n" % 0)
        f.write("// glyphs (NULL where the 8x8 fallback should be used).\n")
        f.write("#define FONT_FIRST %d\n#define FONT_LAST %d\n#define FONT_MAXSCALE 6\n\n" % (FIRST, LAST))
        f.write("extern const int FONT_CELL[FONT_MAXSCALE + 1];\n")
        f.write("extern const unsigned char *const FONT_DATA[FONT_MAXSCALE + 1];\n\n")
        f.write("#endif\n")

    with open(OUT_C, "w") as f:
        f.write("// font_atlas.c — GENERATED by tools/gen-font.py (%s). Do not edit.\n" % fontname)
        f.write('#include "font_atlas.h"\n\n')
        for s in SCALES:
            cell, data = scales_out[s]
            f.write("static const unsigned char g_font%d[%d] = {\n" % (s, len(data)))
            line = []
            for i, byte in enumerate(data):
                line.append(str(byte))
                if len(line) == 32:
                    f.write(",".join(line) + ",\n"); line = []
            if line:
                f.write(",".join(line) + "\n")
            f.write("};\n\n")
        cells = ["0"] * 7
        datas = ["0"] * 7
        for s in SCALES:
            cells[s] = str(8 * s)
            datas[s] = "g_font%d" % s
        f.write("const int FONT_CELL[FONT_MAXSCALE + 1] = {%s};\n" % ",".join(cells))
        f.write("const unsigned char *const FONT_DATA[FONT_MAXSCALE + 1] = {%s};\n" % ",".join(datas))

    print("wrote", OUT_C, "and", OUT_H)

if __name__ == "__main__":
    main()
